'use client';

import { createContext, useContext, useState, useEffect, useCallback } from 'react';

const LanguageContext = createContext();
const STORAGE_KEY = 'wisecare_language';

const LANGUAGES = [
  { code: 'en', name: 'English', native: 'English', flag: '🇬🇧' },
  { code: 'hi', name: 'Hindi', native: 'हिन्दी', flag: '🇮🇳' },
  { code: 'ta', name: 'Tamil', native: 'தமிழ்', flag: '🇮🇳' },
  { code: 'te', name: 'Telugu', native: 'తెలుగు', flag: '🇮🇳' },
  { code: 'bn', name: 'Bengali', native: 'বাংলা', flag: '🇮🇳' },
  { code: 'mr', name: 'Marathi', native: 'मराठी', flag: '🇮🇳' },
  { code: 'kn', name: 'Kannada', native: 'ಕನ್ನಡ', flag: '🇮🇳' },
];

// ─── Translation dictionaries ───
const translations = {
  en: {
    // Nav & Layout
    'nav.dashboard': 'Dashboard',
    'nav.medications': 'Medications',
    'nav.diet': 'Diet & Nutrition',
    'nav.chat': 'AI Companion',
    'nav.emergency': 'Emergency SOS',
    'nav.location': 'Location',
    'nav.appointments': 'Appointments',
    'nav.settings': 'Settings',
    'nav.logout': 'Logout',
    'nav.mainMenu': 'Main Menu',
    'nav.patients': 'My Patients',
    'nav.records': 'Health Records',
    'nav.interactions': 'Drug Interactions',
    'nav.reports': 'Reports',
    'nav.clinical': 'Clinical',
    'nav.account': 'Account',
    'nav.overview': 'Overview',
    'nav.linkedPatients': 'Linked Patients',
    'nav.alerts': 'Alerts',
    'nav.liveLocation': 'Live Location',
    'nav.activityMonitor': 'Activity Monitor',
    'brand.name': 'CareCompanion',
    'brand.tagline': 'AI Healthcare',
    'brand.doctorPortal': 'Doctor Portal',
    'brand.caregiverPortal': 'Caregiver Portal',
    'header.notifications': 'Notifications',
    'header.markAllRead': 'Mark all read',
    'header.searchPatients': 'Search patients...',
    'btn.emergencySOS': 'Emergency SOS',
    'btn.call': 'Call',
    'btn.calling': 'Calling...',
    // Landing Page
    'landing.hackathon': 'AI-Driven Healthcare Hackathon 2025',
    'landing.heroTitle1': 'Compassionate AI Care',
    'landing.heroTitle2': 'for Every Elder',
    'landing.heroDesc': 'Voice-first health companion that empowers elderly individuals to live independently with smart medication management, emergency response, and seamless family connectivity.',
    'landing.getStarted': 'Get Started',
    'landing.startUsing': 'Start Using CareCompanion',
    'landing.watchDemo': 'Watch Demo',
    'landing.heartRate': 'Heart Rate',
    'landing.medicationDue': 'Medication Due',
    'landing.stat1Label': 'Elderly Indians',
    'landing.stat1Sub': 'who need care support',
    'landing.stat2Label': 'Adherence Goal',
    'landing.stat2Sub': 'from 50% baseline',
    'landing.stat3Label': 'SOS Response',
    'landing.stat3Sub': 'emergency alert delivery',
    'landing.stat4Label': 'Languages',
    'landing.stat4Sub': 'regional voice support',
    'landing.featTitle': 'Everything Your Loved One Needs',
    'landing.featDesc': 'Comprehensive care platform designed with empathy, powered by AI',
    'landing.feat1Title': 'AI Voice Companion',
    'landing.feat1Desc': 'Natural voice interaction in 10+ languages',
    'landing.feat2Title': 'Smart Reminders',
    'landing.feat2Desc': 'Never miss a medication or appointment',
    'landing.feat3Title': 'Emergency SOS',
    'landing.feat3Desc': 'One-tap alert to family & emergency services',
    'landing.feat4Title': 'Live Location',
    'landing.feat4Desc': 'Real-time GPS with safe zone alerts',
    'landing.feat5Title': 'Video Consults',
    'landing.feat5Desc': 'Secure video calls with your doctor',
    'landing.feat6Title': 'Health Monitoring',
    'landing.feat6Desc': 'Track vitals, activity & wellness trends',
    'landing.ctaTitle': 'Ready to Give Your Family',
    'landing.ctaTitle2': 'Peace of Mind?',
    'landing.ctaDesc': 'Join thousands of families using CareCompanion AI to keep their elders safe, healthy, and connected.',
    'landing.getStartedFree': 'Get Started Free',
    'landing.footer': 'Built with ❤️ for AI-Driven Healthcare Hackathon 2025 — Empowering Elderly Independence',
    // Login
    'login.welcome': 'Welcome Back',
    'login.subtitle': 'Choose your role to continue',
    'login.patient': 'Patient',
    'login.doctor': 'Doctor',
    'login.caregiver': 'Caregiver',
    // Dashboard
    'dash.welcome': 'Welcome back',
    'dash.upcoming': 'Upcoming',
    'dash.videoCalls': 'Video Calls',
    'dash.completed': 'Completed',
    'dash.today': 'Today',
    // Appointments
    'apt.title': 'Appointments',
    'apt.subtitle': 'Schedule and manage your doctor consultations',
    'apt.book': 'Book Appointment',
    'apt.upcoming': 'Upcoming',
    'apt.past': 'Past',
    'apt.reschedule': 'Reschedule',
    'apt.cancel': 'Cancel',
    'apt.joinVideo': 'Join Video Call',
    'apt.endCall': 'End Call',
    'apt.endComplete': 'End & Mark Complete',
    'apt.bookNew': 'Book New Appointment',
    'apt.scheduleConsult': 'Schedule a consultation with your doctor',
    'apt.doctor': 'Doctor',
    'apt.selectDoctor': 'Select doctor...',
    'apt.date': 'Date',
    'apt.time': 'Time',
    'apt.consultType': 'Consultation Type',
    'apt.videoCall': 'Video Call',
    'apt.inPerson': 'In-Person',
    'apt.reason': 'Reason (optional)',
    'apt.noUpcoming': 'No upcoming appointments',
    'apt.noPast': 'No completed appointments yet',
    'apt.bookToStart': 'Book a new appointment to get started',
    // Language
    'lang.title': 'Language',
    'lang.select': 'Select Language',
  },

  hi: {
    'nav.dashboard': 'डैशबोर्ड',
    'nav.medications': 'दवाइयाँ',
    'nav.diet': 'आहार और पोषण',
    'nav.chat': 'AI सहायक',
    'nav.emergency': 'आपातकालीन SOS',
    'nav.location': 'स्थान',
    'nav.appointments': 'अपॉइंटमेंट',
    'nav.settings': 'सेटिंग्स',
    'nav.logout': 'लॉगआउट',
    'nav.mainMenu': 'मुख्य मेनू',
    'nav.patients': 'मेरे मरीज़',
    'nav.records': 'स्वास्थ्य रिकॉर्ड',
    'nav.interactions': 'दवा इंटरैक्शन',
    'nav.reports': 'रिपोर्ट',
    'nav.clinical': 'क्लिनिकल',
    'nav.account': 'खाता',
    'nav.overview': 'सारांश',
    'nav.linkedPatients': 'जुड़े मरीज़',
    'nav.alerts': 'अलर्ट',
    'nav.liveLocation': 'लाइव स्थान',
    'nav.activityMonitor': 'गतिविधि मॉनिटर',
    'brand.name': 'केयरकम्पेनियन',
    'brand.tagline': 'AI स्वास्थ्य सेवा',
    'brand.doctorPortal': 'डॉक्टर पोर्टल',
    'brand.caregiverPortal': 'देखभालकर्ता पोर्टल',
    'header.notifications': 'सूचनाएँ',
    'header.markAllRead': 'सभी पढ़ा हुआ करें',
    'header.searchPatients': 'मरीज़ खोजें...',
    'btn.emergencySOS': 'आपातकालीन SOS',
    'btn.call': 'कॉल',
    'btn.calling': 'कॉल हो रही है...',
    'landing.hackathon': 'AI-आधारित स्वास्थ्य हैकाथॉन 2025',
    'landing.heroTitle1': 'सहानुभूतिपूर्ण AI देखभाल',
    'landing.heroTitle2': 'हर बुज़ुर्ग के लिए',
    'landing.heroDesc': 'वॉइस-फ़र्स्ट स्वास्थ्य सहायक जो बुज़ुर्गों को स्वतंत्र रूप से जीने में मदद करता है — स्मार्ट दवा प्रबंधन, आपातकालीन प्रतिक्रिया और परिवार से निर्बाध कनेक्टिविटी।',
    'landing.getStarted': 'शुरू करें',
    'landing.startUsing': 'केयरकम्पेनियन शुरू करें',
    'landing.watchDemo': 'डेमो देखें',
    'landing.heartRate': 'हृदय गति',
    'landing.medicationDue': 'दवा का समय',
    'landing.stat1Label': 'भारतीय बुज़ुर्ग',
    'landing.stat1Sub': 'जिन्हें देखभाल की ज़रूरत है',
    'landing.stat2Label': 'अनुपालन लक्ष्य',
    'landing.stat2Sub': '50% आधार रेखा से',
    'landing.stat3Label': 'SOS प्रतिक्रिया',
    'landing.stat3Sub': 'आपातकालीन अलर्ट डिलीवरी',
    'landing.stat4Label': 'भाषाएँ',
    'landing.stat4Sub': 'क्षेत्रीय वॉइस सपोर्ट',
    'landing.featTitle': 'आपके प्रियजनों के लिए सब कुछ',
    'landing.featDesc': 'सहानुभूति से डिज़ाइन, AI-संचालित व्यापक देखभाल प्लेटफ़ॉर्म',
    'landing.feat1Title': 'AI वॉइस सहायक',
    'landing.feat1Desc': '10+ भाषाओं में प्राकृतिक वॉइस इंटरैक्शन',
    'landing.feat2Title': 'स्मार्ट रिमाइंडर',
    'landing.feat2Desc': 'कोई दवा या अपॉइंटमेंट न छूटे',
    'landing.feat3Title': 'आपातकालीन SOS',
    'landing.feat3Desc': 'परिवार और आपातकालीन सेवाओं को एक-टैप अलर्ट',
    'landing.feat4Title': 'लाइव स्थान',
    'landing.feat4Desc': 'सुरक्षित ज़ोन अलर्ट के साथ रियल-टाइम GPS',
    'landing.feat5Title': 'वीडियो परामर्श',
    'landing.feat5Desc': 'डॉक्टर के साथ सुरक्षित वीडियो कॉल',
    'landing.feat6Title': 'स्वास्थ्य मॉनिटरिंग',
    'landing.feat6Desc': 'वाइटल्स, गतिविधि और वेलनेस ट्रैक करें',
    'landing.ctaTitle': 'अपने परिवार को',
    'landing.ctaTitle2': 'मन की शांति दें?',
    'landing.ctaDesc': 'हज़ारों परिवार CareCompanion AI का उपयोग कर रहे हैं अपने बुज़ुर्गों को सुरक्षित, स्वस्थ और जुड़ा रखने के लिए।',
    'landing.getStartedFree': 'मुफ़्त शुरू करें',
    'landing.footer': 'AI-आधारित स्वास्थ्य हैकाथॉन 2025 के लिए ❤️ से बनाया — बुज़ुर्ग स्वतंत्रता को सशक्त बनाना',
    'login.welcome': 'वापसी पर स्वागत',
    'login.subtitle': 'जारी रखने के लिए अपनी भूमिका चुनें',
    'login.patient': 'मरीज़',
    'login.doctor': 'डॉक्टर',
    'login.caregiver': 'देखभालकर्ता',
    'dash.welcome': 'वापसी पर स्वागत',
    'dash.upcoming': 'आगामी',
    'dash.videoCalls': 'वीडियो कॉल',
    'dash.completed': 'पूर्ण',
    'dash.today': 'आज',
    'apt.title': 'अपॉइंटमेंट',
    'apt.subtitle': 'अपने डॉक्टर परामर्श शेड्यूल और प्रबंधित करें',
    'apt.book': 'अपॉइंटमेंट बुक करें',
    'apt.upcoming': 'आगामी',
    'apt.past': 'पिछले',
    'apt.reschedule': 'पुनर्निर्धारित',
    'apt.cancel': 'रद्द करें',
    'apt.joinVideo': 'वीडियो कॉल जुड़ें',
    'apt.endCall': 'कॉल समाप्त',
    'apt.endComplete': 'समाप्त और पूर्ण करें',
    'apt.bookNew': 'नई अपॉइंटमेंट बुक करें',
    'apt.scheduleConsult': 'अपने डॉक्टर के साथ परामर्श शेड्यूल करें',
    'apt.doctor': 'डॉक्टर',
    'apt.selectDoctor': 'डॉक्टर चुनें...',
    'apt.date': 'तारीख',
    'apt.time': 'समय',
    'apt.consultType': 'परामर्श प्रकार',
    'apt.videoCall': 'वीडियो कॉल',
    'apt.inPerson': 'व्यक्तिगत',
    'apt.reason': 'कारण (वैकल्पिक)',
    'apt.noUpcoming': 'कोई आगामी अपॉइंटमेंट नहीं',
    'apt.noPast': 'अभी तक कोई पूर्ण अपॉइंटमेंट नहीं',
    'apt.bookToStart': 'शुरू करने के लिए नई अपॉइंटमेंट बुक करें',
    'lang.title': 'भाषा',
    'lang.select': 'भाषा चुनें',
  },

  ta: {
    'nav.dashboard': 'டாஷ்போர்டு',
    'nav.medications': 'மருந்துகள்',
    'nav.diet': 'உணவு & ஊட்டச்சத்து',
    'nav.chat': 'AI துணையர்',
    'nav.emergency': 'அவசர SOS',
    'nav.location': 'இருப்பிடம்',
    'nav.appointments': 'சந்திப்புகள்',
    'nav.settings': 'அமைப்புகள்',
    'nav.logout': 'வெளியேறு',
    'nav.mainMenu': 'முதன்மை மெனு',
    'nav.patients': 'எனது நோயாளிகள்',
    'nav.records': 'சுகாதார பதிவுகள்',
    'nav.interactions': 'மருந்து தொடர்பு',
    'nav.reports': 'அறிக்கைகள்',
    'nav.clinical': 'மருத்துவ',
    'nav.account': 'கணக்கு',
    'nav.overview': 'கண்ணோட்டம்',
    'nav.linkedPatients': 'இணைந்த நோயாளிகள்',
    'nav.alerts': 'எச்சரிக்கைகள்',
    'nav.liveLocation': 'நேரடி இருப்பிடம்',
    'nav.activityMonitor': 'செயல்பாட்டு கண்காணிப்பு',
    'brand.name': 'கேர்காம்பேனியன்',
    'brand.tagline': 'AI சுகாதாரம்',
    'brand.doctorPortal': 'மருத்துவர் போர்டல்',
    'brand.caregiverPortal': 'பராமரிப்பாளர் போர்டல்',
    'header.notifications': 'அறிவிப்புகள்',
    'header.markAllRead': 'அனைத்தும் படித்ததாக',
    'header.searchPatients': 'நோயாளிகள் தேடு...',
    'btn.emergencySOS': 'அவசர SOS',
    'btn.call': 'அழைப்பு',
    'btn.calling': 'அழைக்கிறது...',
    'landing.hackathon': 'AI-சுகாதார ஹேக்கத்தான் 2025',
    'landing.heroTitle1': 'இரக்கமுள்ள AI கவனிப்பு',
    'landing.heroTitle2': 'ஒவ்வொரு முதியவருக்கும்',
    'landing.heroDesc': 'முதியவர்களை சுதந்திரமாக வாழ உதவும் குரல்-முதல் சுகாதார துணையர் — மருந்து மேலாண்மை, அவசர பதில் மற்றும் குடும்ப இணைப்பு.',
    'landing.getStarted': 'தொடங்கு',
    'landing.startUsing': 'கேர்காம்பேனியன் தொடங்கு',
    'landing.watchDemo': 'டெமோ பாருங்கள்',
    'landing.heartRate': 'இதய துடிப்பு',
    'landing.medicationDue': 'மருந்து நேரம்',
    'landing.stat1Label': 'இந்திய முதியவர்கள்',
    'landing.stat1Sub': 'கவனிப்பு தேவை',
    'landing.stat2Label': 'இணக்க இலக்கு',
    'landing.stat2Sub': '50% அடிப்படையிலிருந்து',
    'landing.stat3Label': 'SOS பதில்',
    'landing.stat3Sub': 'அவசர எச்சரிக்கை',
    'landing.stat4Label': 'மொழிகள்',
    'landing.stat4Sub': 'பிராந்திய குரல் ஆதரவு',
    'landing.featTitle': 'உங்கள் அன்பானவருக்கு தேவையான அனைத்தும்',
    'landing.featDesc': 'இரக்கத்துடன் வடிவமைக்கப்பட்ட, AI-சார்ந்த விரிவான கவனிப்பு',
    'landing.feat1Title': 'AI குரல் துணையர்',
    'landing.feat1Desc': '10+ மொழிகளில் இயற்கையான குரல் உரையாடல்',
    'landing.feat2Title': 'ஸ்மார்ட் நினைவூட்டல்',
    'landing.feat2Desc': 'எந்த மருந்தும் சந்திப்பும் தவறாது',
    'landing.feat3Title': 'அவசர SOS',
    'landing.feat3Desc': 'குடும்பத்திற்கு ஒரு-தட்டு எச்சரிக்கை',
    'landing.feat4Title': 'நேரடி இருப்பிடம்',
    'landing.feat4Desc': 'பாதுகாப்பு மண்டல எச்சரிக்கையுடன் GPS',
    'landing.feat5Title': 'வீடியோ ஆலோசனை',
    'landing.feat5Desc': 'மருத்துவருடன் பாதுகாப்பான வீடியோ அழைப்பு',
    'landing.feat6Title': 'ஆரோக்கிய கண்காணிப்பு',
    'landing.feat6Desc': 'உயிர்சின்னங்கள் மற்றும் ஆரோக்கிய போக்குகள்',
    'landing.ctaTitle': 'உங்கள் குடும்பத்திற்கு',
    'landing.ctaTitle2': 'மன அமைதி தரலாமா?',
    'landing.ctaDesc': 'ஆயிரக்கணக்கான குடும்பங்கள் CareCompanion AI பயன்படுத்துகின்றன.',
    'landing.getStartedFree': 'இலவசமாக தொடங்கு',
    'landing.footer': 'AI-சுகாதார ஹேக்கத்தான் 2025 — முதியவர் சுதந்திரம்',
    'login.welcome': 'மீண்டும் வரவேற்கிறோம்',
    'login.subtitle': 'தொடர உங்கள் பங்கைத் தேர்ந்தெடுக்கவும்',
    'login.patient': 'நோயாளி',
    'login.doctor': 'மருத்துவர்',
    'login.caregiver': 'பராமரிப்பாளர்',
    'dash.welcome': 'மீண்டும் வரவேற்கிறோம்',
    'dash.upcoming': 'வரவிருக்கும்',
    'dash.videoCalls': 'வீடியோ அழைப்புகள்',
    'dash.completed': 'நிறைவு',
    'dash.today': 'இன்று',
    'apt.title': 'சந்திப்புகள்',
    'apt.subtitle': 'மருத்துவர் ஆலோசனைகளை திட்டமிடுங்கள்',
    'apt.book': 'சந்திப்பு பதிவு',
    'apt.upcoming': 'வரவிருக்கும்',
    'apt.past': 'முந்தைய',
    'apt.reschedule': 'மீள்திட்டமிடு',
    'apt.cancel': 'ரத்து',
    'apt.joinVideo': 'வீடியோ அழைப்பு',
    'apt.endCall': 'அழைப்பு முடி',
    'apt.endComplete': 'முடித்து நிறைவு செய்',
    'apt.bookNew': 'புதிய சந்திப்பு பதிவு',
    'apt.scheduleConsult': 'மருத்துவருடன் ஆலோசனை திட்டமிடுங்கள்',
    'apt.doctor': 'மருத்துவர்',
    'apt.selectDoctor': 'மருத்துவர் தேர்வு...',
    'apt.date': 'தேதி',
    'apt.time': 'நேரம்',
    'apt.consultType': 'ஆலோசனை வகை',
    'apt.videoCall': 'வீடியோ அழைப்பு',
    'apt.inPerson': 'நேரில்',
    'apt.reason': 'காரணம் (விருப்பம்)',
    'apt.noUpcoming': 'வரவிருக்கும் சந்திப்புகள் இல்லை',
    'apt.noPast': 'நிறைவான சந்திப்புகள் இல்லை',
    'apt.bookToStart': 'தொடங்க புதிய சந்திப்பு பதிவு செய்க',
    'lang.title': 'மொழி',
    'lang.select': 'மொழி தேர்வு',
  },

  te: {
    'nav.dashboard': 'డాష్‌బోర్డ్',
    'nav.medications': 'మందులు',
    'nav.diet': 'ఆహారం & పోషణ',
    'nav.chat': 'AI సహాయకుడు',
    'nav.emergency': 'అత్యవసర SOS',
    'nav.location': 'స్థానం',
    'nav.appointments': 'అపాయింట్‌మెంట్లు',
    'nav.settings': 'సెట్టింగ్‌లు',
    'nav.logout': 'లాగ్‌అవుట్',
    'nav.mainMenu': 'ప్రధాన మెనూ',
    'nav.patients': 'నా రోగులు',
    'nav.records': 'ఆరోగ్య రికార్డులు',
    'nav.interactions': 'మందు పరస్పర చర్యలు',
    'nav.reports': 'నివేదికలు',
    'nav.clinical': 'క్లినికల్',
    'nav.account': 'ఖాతా',
    'nav.overview': 'అవలోకనం',
    'nav.linkedPatients': 'అనుసంధాన రోగులు',
    'nav.alerts': 'హెచ్చరికలు',
    'nav.liveLocation': 'లైవ్ స్థానం',
    'nav.activityMonitor': 'కార్యాచరణ మానిటర్',
    'brand.name': 'కేర్‌కంపానియన్',
    'brand.tagline': 'AI ఆరోగ్య సేవ',
    'brand.doctorPortal': 'డాక్టర్ పోర్టల్',
    'brand.caregiverPortal': 'సంరక్షకుడి పోర్టల్',
    'header.notifications': 'నోటిఫికేషన్లు',
    'header.markAllRead': 'అన్నీ చదివినట్లు',
    'header.searchPatients': 'రోగులను వెతకండి...',
    'btn.emergencySOS': 'అత్యవసర SOS',
    'btn.call': 'కాల్',
    'btn.calling': 'కాల్ చేస్తోంది...',
    'landing.hackathon': 'AI-ఆరోగ్య హ్యాకథాన్ 2025',
    'landing.heroTitle1': 'కరుణతో AI సంరక్షణ',
    'landing.heroTitle2': 'ప్రతి వృద్ధుడికి',
    'landing.heroDesc': 'వృద్ధులను స్వతంత్రంగా జీవించడానికి సహాయపడే వాయిస్-ఫస్ట్ ఆరోగ్య సహాయకుడు.',
    'landing.getStarted': 'ప్రారంభించండి',
    'landing.startUsing': 'కేర్‌కంపానియన్ ప్రారంభించండి',
    'landing.watchDemo': 'డెమో చూడండి',
    'landing.heartRate': 'హృదయ స్పందన',
    'landing.medicationDue': 'మందు సమయం',
    'landing.stat1Label': 'భారతీయ వృద్ధులు',
    'landing.stat1Sub': 'సంరక్షణ అవసరం',
    'landing.stat2Label': 'సమ్మతి లక్ష్యం',
    'landing.stat2Sub': '50% బేస్‌లైన్ నుండి',
    'landing.stat3Label': 'SOS ప్రతిస్పందన',
    'landing.stat3Sub': 'అత్యవసర హెచ్చరిక',
    'landing.stat4Label': 'భాషలు',
    'landing.stat4Sub': 'ప్రాంతీయ వాయిస్ మద్దతు',
    'landing.featTitle': 'మీ ప్రియమైనవారికి అవసరమైనవన్నీ',
    'landing.featDesc': 'కరుణతో రూపొందించబడిన, AI-ఆధారిత సమగ్ర సంరక్షణ',
    'landing.feat1Title': 'AI వాయిస్ సహాయకుడు',
    'landing.feat1Desc': '10+ భాషలలో సహజ వాయిస్ ఇంటరాక్షన్',
    'landing.feat2Title': 'స్మార్ట్ రిమైండర్లు',
    'landing.feat2Desc': 'ఏ మందు లేదా అపాయింట్‌మెంట్ మిస్ కాదు',
    'landing.feat3Title': 'అత్యవసర SOS',
    'landing.feat3Desc': 'కుటుంబానికి ఒక-ట్యాప్ అలర్ట్',
    'landing.feat4Title': 'లైవ్ స్థానం',
    'landing.feat4Desc': 'సేఫ్ జోన్ అలర్ట్‌లతో GPS',
    'landing.feat5Title': 'వీడియో సంప్రదింపులు',
    'landing.feat5Desc': 'డాక్టర్‌తో సురక్షిత వీడియో కాల్',
    'landing.feat6Title': 'ఆరోగ్య పర్యవేక్షణ',
    'landing.feat6Desc': 'వైటల్స్ మరియు ఆరోగ్య ట్రెండ్‌లు ట్రాక్ చేయండి',
    'landing.ctaTitle': 'మీ కుటుంబానికి',
    'landing.ctaTitle2': 'మనశ్శాంతి ఇవ్వాలా?',
    'landing.ctaDesc': 'వేలాది కుటుంబాలు CareCompanion AI వాడుతున్నాయి.',
    'landing.getStartedFree': 'ఉచితంగా ప్రారంభించండి',
    'landing.footer': 'AI-ఆరోగ్య హ్యాకథాన్ 2025 — వృద్ధుల స్వాతంత్ర్యం',
    'login.welcome': 'తిరిగి స్వాగతం',
    'login.subtitle': 'కొనసాగించడానికి మీ పాత్రను ఎంచుకోండి',
    'login.patient': 'రోగి',
    'login.doctor': 'డాక్టర్',
    'login.caregiver': 'సంరక్షకుడు',
    'dash.welcome': 'తిరిగి స్వాగతం',
    'dash.upcoming': 'రాబోయే',
    'dash.videoCalls': 'వీడియో కాల్‌లు',
    'dash.completed': 'పూర్తయింది',
    'dash.today': 'ఈరోజు',
    'apt.title': 'అపాయింట్‌మెంట్లు',
    'apt.subtitle': 'మీ డాక్టర్ సంప్రదింపులను షెడ్యూల్ చేయండి',
    'apt.book': 'అపాయింట్‌మెంట్ బుక్',
    'apt.upcoming': 'రాబోయే',
    'apt.past': 'గతం',
    'apt.reschedule': 'మళ్ళీ షెడ్యూల్',
    'apt.cancel': 'రద్దు',
    'apt.joinVideo': 'వీడియో కాల్ చేరండి',
    'apt.endCall': 'కాల్ ముగించు',
    'apt.endComplete': 'ముగించి పూర్తి చేయి',
    'apt.bookNew': 'కొత్త అపాయింట్‌మెంట్ బుక్',
    'apt.scheduleConsult': 'మీ డాక్టర్‌తో సంప్రదింపు షెడ్యూల్ చేయండి',
    'apt.doctor': 'డాక్టర్',
    'apt.selectDoctor': 'డాక్టర్ ఎంచుకోండి...',
    'apt.date': 'తేదీ',
    'apt.time': 'సమయం',
    'apt.consultType': 'సంప్రదింపు రకం',
    'apt.videoCall': 'వీడియో కాల్',
    'apt.inPerson': 'వ్యక్తిగతంగా',
    'apt.reason': 'కారణం (ఐచ్ఛికం)',
    'apt.noUpcoming': 'రాబోయే అపాయింట్‌మెంట్లు లేవు',
    'apt.noPast': 'పూర్తయిన అపాయింట్‌మెంట్లు లేవు',
    'apt.bookToStart': 'ప్రారంభించడానికి కొత్త అపాయింట్‌మెంట్ బుక్ చేయండి',
    'lang.title': 'భాష',
    'lang.select': 'భాష ఎంచుకోండి',
  },

  bn: {
    'nav.dashboard': 'ড্যাশবোর্ড',
    'nav.medications': 'ওষুধ',
    'nav.diet': 'খাদ্য ও পুষ্টি',
    'nav.chat': 'AI সহায়ক',
    'nav.emergency': 'জরুরি SOS',
    'nav.location': 'অবস্থান',
    'nav.appointments': 'অ্যাপয়েন্টমেন্ট',
    'nav.settings': 'সেটিংস',
    'nav.logout': 'লগআউট',
    'nav.mainMenu': 'প্রধান মেনু',
    'nav.patients': 'আমার রোগীরা',
    'nav.records': 'স্বাস্থ্য রেকর্ড',
    'nav.interactions': 'ওষুধ মিথস্ক্রিয়া',
    'nav.reports': 'রিপোর্ট',
    'nav.clinical': 'ক্লিনিক্যাল',
    'nav.account': 'অ্যাকাউন্ট',
    'nav.overview': 'সারসংক্ষেপ',
    'nav.linkedPatients': 'সংযুক্ত রোগী',
    'nav.alerts': 'সতর্কতা',
    'nav.liveLocation': 'লাইভ অবস্থান',
    'nav.activityMonitor': 'কার্যকলাপ মনিটর',
    'brand.name': 'কেয়ারকম্পানিয়ন',
    'brand.tagline': 'AI স্বাস্থ্যসেবা',
    'brand.doctorPortal': 'ডাক্তার পোর্টাল',
    'brand.caregiverPortal': 'পরিচর্যাকারী পোর্টাল',
    'header.notifications': 'বিজ্ঞপ্তি',
    'header.markAllRead': 'সব পড়া হয়েছে',
    'header.searchPatients': 'রোগী খুঁজুন...',
    'btn.emergencySOS': 'জরুরি SOS',
    'btn.call': 'কল',
    'btn.calling': 'কল হচ্ছে...',
    'landing.hackathon': 'AI-স্বাস্থ্য হ্যাকাথন ২০২৫',
    'landing.heroTitle1': 'সহানুভূতিশীল AI যত্ন',
    'landing.heroTitle2': 'প্রতিটি প্রবীণের জন্য',
    'landing.heroDesc': 'প্রবীণদের স্বাধীনভাবে বাঁচতে সাহায্যকারী ভয়েস-ফার্স্ট স্বাস্থ্য সহায়ক।',
    'landing.getStarted': 'শুরু করুন',
    'landing.startUsing': 'কেয়ারকম্পানিয়ন শুরু করুন',
    'landing.watchDemo': 'ডেমো দেখুন',
    'landing.heartRate': 'হৃদ স্পন্দন',
    'landing.medicationDue': 'ওষুধের সময়',
    'landing.featTitle': 'আপনার প্রিয়জনের যা কিছু দরকার',
    'landing.featDesc': 'সহানুভূতি দিয়ে ডিজাইন করা, AI-চালিত যত্ন প্ল্যাটফর্ম',
    'landing.ctaTitle': 'আপনার পরিবারকে',
    'landing.ctaTitle2': 'মানসিক শান্তি দিন?',
    'landing.ctaDesc': 'হাজার হাজার পরিবার CareCompanion AI ব্যবহার করছে।',
    'landing.getStartedFree': 'বিনামূল্যে শুরু করুন',
    'login.welcome': 'আবার স্বাগতম',
    'login.subtitle': 'চালিয়ে যেতে আপনার ভূমিকা বেছে নিন',
    'login.patient': 'রোগী',
    'login.doctor': 'ডাক্তার',
    'login.caregiver': 'পরিচর্যাকারী',
    'dash.welcome': 'আবার স্বাগতম',
    'apt.title': 'অ্যাপয়েন্টমেন্ট',
    'apt.book': 'অ্যাপয়েন্টমেন্ট বুক',
    'lang.title': 'ভাষা',
    'lang.select': 'ভাষা নির্বাচন',
  },

  mr: {
    'nav.dashboard': 'डॅशबोर्ड',
    'nav.medications': 'औषधे',
    'nav.diet': 'आहार आणि पोषण',
    'nav.chat': 'AI सहाय्यक',
    'nav.emergency': 'आणीबाणी SOS',
    'nav.location': 'स्थान',
    'nav.appointments': 'भेटी',
    'nav.settings': 'सेटिंग्ज',
    'nav.logout': 'लॉगआउट',
    'nav.mainMenu': 'मुख्य मेनू',
    'nav.patients': 'माझे रुग्ण',
    'nav.records': 'आरोग्य नोंदी',
    'nav.interactions': 'औषध परस्परक्रिया',
    'nav.reports': 'अहवाल',
    'nav.clinical': 'क्लिनिकल',
    'nav.account': 'खाते',
    'nav.overview': 'सारांश',
    'nav.linkedPatients': 'जोडलेले रुग्ण',
    'nav.alerts': 'सूचना',
    'nav.liveLocation': 'लाइव स्थान',
    'nav.activityMonitor': 'क्रियाकलाप मॉनिटर',
    'brand.name': 'केअरकम्पॅनियन',
    'brand.tagline': 'AI आरोग्यसेवा',
    'brand.doctorPortal': 'डॉक्टर पोर्टल',
    'brand.caregiverPortal': 'काळजीवाहक पोर्टल',
    'header.notifications': 'सूचना',
    'header.markAllRead': 'सर्व वाचलेले',
    'header.searchPatients': 'रुग्ण शोधा...',
    'btn.emergencySOS': 'आणीबाणी SOS',
    'btn.call': 'कॉल',
    'btn.calling': 'कॉल होत आहे...',
    'landing.hackathon': 'AI-आरोग्य हॅकॅथॉन 2025',
    'landing.heroTitle1': 'सहानुभूतीपूर्ण AI काळजी',
    'landing.heroTitle2': 'प्रत्येक ज्येष्ठांसाठी',
    'landing.heroDesc': 'ज्येष्ठांना स्वतंत्रपणे जगण्यास मदत करणारा वॉइस-फर्स्ट आरोग्य सहाय्यक.',
    'landing.getStarted': 'सुरू करा',
    'landing.startUsing': 'केअरकम्पॅनियन सुरू करा',
    'landing.watchDemo': 'डेमो पहा',
    'landing.featTitle': 'तुमच्या प्रियजनांना हवे ते सर्व',
    'landing.featDesc': 'सहानुभूतीने तयार केलेले AI-आधारित काळजी प्लॅटफॉर्म',
    'landing.ctaTitle': 'तुमच्या कुटुंबाला',
    'landing.ctaTitle2': 'मनःशांती द्यायची?',
    'landing.getStartedFree': 'मोफत सुरू करा',
    'login.welcome': 'पुन्हा स्वागत',
    'login.subtitle': 'पुढे जाण्यासाठी तुमची भूमिका निवडा',
    'login.patient': 'रुग्ण',
    'login.doctor': 'डॉक्टर',
    'login.caregiver': 'काळजीवाहक',
    'dash.welcome': 'पुन्हा स्वागत',
    'apt.title': 'भेटी',
    'apt.book': 'भेट बुक करा',
    'lang.title': 'भाषा',
    'lang.select': 'भाषा निवडा',
  },

  kn: {
    'nav.dashboard': 'ಡ್ಯಾಶ್‌ಬೋರ್ಡ್',
    'nav.medications': 'ಔಷಧಿಗಳು',
    'nav.diet': 'ಆಹಾರ ಮತ್ತು ಪೋಷಣೆ',
    'nav.chat': 'AI ಸಹಾಯಕ',
    'nav.emergency': 'ತುರ್ತು SOS',
    'nav.location': 'ಸ್ಥಳ',
    'nav.appointments': 'ಅಪಾಯಿಂಟ್‌ಮೆಂಟ್‌ಗಳು',
    'nav.settings': 'ಸೆಟ್ಟಿಂಗ್‌ಗಳು',
    'nav.logout': 'ಲಾಗ್‌ಔಟ್',
    'nav.mainMenu': 'ಮುಖ್ಯ ಮೆನು',
    'nav.patients': 'ನನ್ನ ರೋಗಿಗಳು',
    'nav.records': 'ಆರೋಗ್ಯ ದಾಖಲೆಗಳು',
    'nav.interactions': 'ಔಷಧ ಪರಸ್ಪರ ಕ್ರಿಯೆ',
    'nav.reports': 'ವರದಿಗಳು',
    'nav.clinical': 'ಕ್ಲಿನಿಕಲ್',
    'nav.account': 'ಖಾತೆ',
    'nav.overview': 'ಅವಲೋಕನ',
    'nav.linkedPatients': 'ಸಂಪರ್ಕಿತ ರೋಗಿಗಳು',
    'nav.alerts': 'ಎಚ್ಚರಿಕೆಗಳು',
    'nav.liveLocation': 'ಲೈವ್ ಸ್ಥಳ',
    'nav.activityMonitor': 'ಚಟುವಟಿಕೆ ಮಾನಿಟರ್',
    'brand.name': 'ಕೇರ್‌ಕಂಪ್ಯಾನಿಯನ್',
    'brand.tagline': 'AI ಆರೋಗ್ಯ ಸೇವೆ',
    'brand.doctorPortal': 'ವೈದ್ಯರ ಪೋರ್ಟಲ್',
    'brand.caregiverPortal': 'ಆರೈಕೆದಾರ ಪೋರ್ಟಲ್',
    'header.notifications': 'ಅಧಿಸೂಚನೆಗಳು',
    'header.markAllRead': 'ಎಲ್ಲಾ ಓದಲಾಗಿದೆ',
    'header.searchPatients': 'ರೋಗಿಗಳನ್ನು ಹುಡುಕಿ...',
    'btn.emergencySOS': 'ತುರ್ತು SOS',
    'btn.call': 'ಕರೆ',
    'btn.calling': 'ಕರೆ ಮಾಡುತ್ತಿದೆ...',
    'landing.heroTitle1': 'ಕರುಣಾಮಯ AI ಆರೈಕೆ',
    'landing.heroTitle2': 'ಪ್ರತಿ ಹಿರಿಯರಿಗಾಗಿ',
    'landing.getStarted': 'ಪ್ರಾರಂಭಿಸಿ',
    'landing.featTitle': 'ನಿಮ್ಮ ಪ್ರೀತಿಪಾತ್ರರಿಗೆ ಬೇಕಾದ ಎಲ್ಲವೂ',
    'landing.getStartedFree': 'ಉಚಿತವಾಗಿ ಪ್ರಾರಂಭಿಸಿ',
    'login.welcome': 'ಮತ್ತೆ ಸ್ವಾಗತ',
    'login.subtitle': 'ಮುಂದುವರಿಸಲು ನಿಮ್ಮ ಪಾತ್ರವನ್ನು ಆಯ್ಕೆಮಾಡಿ',
    'login.patient': 'ರೋಗಿ',
    'login.doctor': 'ವೈದ್ಯರು',
    'login.caregiver': 'ಆರೈಕೆದಾರ',
    'dash.welcome': 'ಮತ್ತೆ ಸ್ವಾಗತ',
    'apt.title': 'ಅಪಾಯಿಂಟ್‌ಮೆಂಟ್‌ಗಳು',
    'apt.book': 'ಅಪಾಯಿಂಟ್‌ಮೆಂಟ್ ಬುಕ್',
    'lang.title': 'ಭಾಷೆ',
    'lang.select': 'ಭಾಷೆ ಆಯ್ಕೆಮಾಡಿ',
  },
};

export function LanguageProvider({ children }) {
  const [language, setLanguage] = useState('en');
  const [hydrated, setHydrated] = useState(false);

  useEffect(() => {
    const stored = localStorage.getItem(STORAGE_KEY);
    if (stored && translations[stored]) setLanguage(stored);
    setHydrated(true);
  }, []);

  const changeLanguage = useCallback((code) => {
    setLanguage(code);
    localStorage.setItem(STORAGE_KEY, code);
  }, []);

  const t = useCallback((key) => {
    const dict = translations[language] || translations.en;
    return dict[key] || translations.en[key] || key;
  }, [language]);

  return (
    <LanguageContext.Provider value={{ language, changeLanguage, t, languages: LANGUAGES, hydrated }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const ctx = useContext(LanguageContext);
  if (!ctx) throw new Error('useLanguage must be used within LanguageProvider');
  return ctx;
}

export { LANGUAGES };
